services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: pablo
      WORDPRESS_DB_PASSWORD: 123!
      WORDPRESS_DB_NAME: ns
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ns
      MYSQL_USER: pablo
      MYSQL_PASSWORD: 123!
      MYSQL_ROOT_PASSWORD: 321!
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


